name: rum android test
on: push
jobs:
  run-mobile-tests:
    runs-on: macos-latest

    steps:
      - name: setup java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17.0.11'
      - name: pull the project in to the runner
        uses: actions/checkout@v3

      - name: setup appium
        run: |
          npm install -g appium@2.5.3
          appium -v
          appium &>/dev/null &

      - name: run appium android tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          arch: arm64-v8a
          api-level: 30  # Specify the API level here
          script: mvn clean test -Pandroid
          target: default
          cores: 2
          avd-name: test
          force-avd-creation: true
          emulator-boot-timeout: 600
          emulator-options: -no-window -gpu swiftshader_indirect -no-snapshot -noaudio -no-boot-anim
          disable-animations: true
          disable-spellchecker: false
          disable-linux-hw-accel: auto
          enable-hw-keyboard: false
          channel: stable
  env:
    JAVA_HOME: /Users/runner/hostedtoolcache/Java_Temurin-Hotspot_jdk/17.0.11-9/arm64/Contents/Home
    runs-on:
    JAVA_HOME_17_ARM64: /Users/runner/hostedtoolcache/Java_Temurin-Hotspot_jdk/17.0.11-9/arm64/Contents/Home

